# Generated by Django 4.2.2 on 2024-06-24 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = []
