# Generated by Django 4.2.2 on 2024-06-24 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_auto_20240624_1923"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videocourse",
            name="_id",
        ),
        migrations.AddField(
            model_name="videocourse",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
    ]
