# Generated by Django 4.2.2 on 2023-08-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_myuser_date_joined_alter_myuser_is_superuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
