# Generated by Django 4.2.2 on 2023-08-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_myuser_reset_password_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="reset_password_token",
        ),
    ]
