# Generated by Django 4.2.2 on 2023-08-07 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_remove_myuser_reset_password_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="reset_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
