# Generated by Django 4.2.2 on 2024-02-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_videocourse_product_video_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="video_course",
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="image",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
