# Generated by Django 4.2.2 on 2024-05-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True, default="/placeholder.png", null=True, upload_to=""
            ),
        ),
    ]
