# Generated by Django 4.2.2 on 2024-06-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_article_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="id",
        ),
        migrations.AddField(
            model_name="article",
            name="_id",
            field=models.AutoField(
                default=1, editable=False, primary_key=True, serialize=False
            ),
            preserve_default=False,
        ),
    ]
